name: Run examples

on:
  pull_request:
    paths:
      - '.github/workflows/examples.yml'
      - 'examples/**.py'
      - 'cmaes/**.py'

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group optional --group benchmark
      - run: uv run python examples/quadratic_2d_function.py
      - run: uv run python examples/ipop_cma.py
      - run: uv run python examples/bipop_cma.py
      - run: uv run python examples/ellipsoid_function.py
      - run: uv run python examples/optuna_sampler.py
      - run: uv run python examples/lra_cma.py
      - run: uv run python examples/ws_cma.py
      - run: uv run python examples/cma_with_margin_binary.py
      - run: uv run python examples/cma_with_margin_integer.py
      - run: uv run python examples/safecma.py
      - run: uv run python examples/cma_sop.py
  examples-cmawm-without-scipy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync
      - run: uv run python examples/cma_with_margin_binary.py
      - run: uv run python examples/cma_with_margin_integer.py
