name: Publish distributions to TestPyPI and PyPI

on:
  push:
    tags:
    - v*.*.*

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.x'

    - name: Build distribution packages
      run: uv build --sdist --wheel --no-sources
    - name: Verify the distributions
      run: uvx twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: distribution
        path: dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
        gh release create ${TAGNAME} --draft dist/*
