name: Run tests and linters

on:
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'setup.cfg'
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools numpy scipy
          pip install --progress-bar off -r requirements-dev.txt
      - run: flake8 . --show-source --statistics
      - run: black --check .
      - run: mypy cmaes
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools numpy scipy hypothesis
          pip install --progress-bar off .
      - run: python -m unittest
