name: Run tests and linters

on:
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'pyproject.toml'
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync --group dev --group optional
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run mypy cmaes
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group dev --group optional
      - run: uv run pytest tests

